name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
    - name: Build with Maven
      run: mvn -Dproduction -B package --file pom.xml
    - uses: actions/upload-artifact@master
      with:
        name: docker-spring-boot.jar
        path: docker-spring-boot-2.0-SNAPSHOT.jar
